# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20170110_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lists.List'),
        ),
        migrations.AlterField(
            model_name='list',
            name='text',
            field=models.TextField(default='', null=True),
        ),
    ]
