# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20170112_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
