# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_list_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='text',
        ),
    ]
